# Generated by Django 5.2.12 on 2026-03-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0005_dining_hotel_hotelbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dining',
        ),
    ]
