# Generated by Django 5.2.12 on 2026-03-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0006_delete_dining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelBooking',
        ),
    ]
