# Generated by Django 5.2.12 on 2026-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0008_hotel_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time',
            field=models.CharField(default='Oct to Mar', max_length=200),
        ),
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Mountains', 'Mountains'), ('Heritage', 'Heritage'), ('Romantic', 'Romantic'), ('City Break', 'City Break'), ('Adventure', 'Adventure')], default='Adventure', max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='reach_info',
            field=models.TextField(blank=True, default='Well connected by flights and trains.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='visa_info',
            field=models.TextField(blank=True, default='Visa on Arrival available for most tourists.'),
        ),
    ]
