# Generated by Django 5.2.12 on 2026-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0009_destination_best_time_destination_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='sub_region',
            field=models.CharField(blank=True, default='Primary', max_length=100),
        ),
    ]
